# Site settings
title: The Coder's Journey 
header-img: img/home-bg.png
email: kevinladkins@gmail.com
copyright_name: kevinladkins
description: > # this means to ignore newlines until "baseurl:"
  Exploring strange new (digital) worlds... 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: kevinladkins
github_username:  kevinladkins
learn_profile: kevinladkins
email_username: kevinladkins@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
